#!/bin/sh

# Pre-commit hook to run code quality tools
# Based on the original Husky pre-commit hook

docker compose exec -T app composer rector:fix
docker compose exec -T app composer pint:fix
docker compose exec -T app yarn prettier:fix
git add .
