#!/bin/sh

# Pre-commit hook to run code quality tools
# Based on the original Husky pre-commit hook

set -e

docker compose exec -T app ./vendor/bin/rector process --no-progress-bar
docker compose exec -T app ./vendor/bin/pint --dirty

git add -A
