version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: laravel_app

    volumes:
      - .:/app

    ports:
      - "8000:8000"
      - "9003:9003"

    depends_on:
      - postgres
      - redis
      - rabbitmq

    environment:
      # App
      APP_ENV: local
      APP_DEBUG: "true"

      # Database
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret

      # Xdebug
      XDEBUG_MODE: debug,coverage
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      PHP_IDE_CONFIG: serverName=orderflux

      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
