version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: laravel_app

    env_file:
      - .env

    volumes:
      - .:/opt/project
    working_dir: /opt/project

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis
      - rabbitmq

    networks:
      - app_postgres
      - app_redis
      - app_rabbitmq

    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16
    container_name: postgres

    env_file:
      - .env

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - app_postgres

  redis:
    image: redis:7-alpine
    container_name: redis

    networks:
      - app_redis

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq

    env_file:
      - .env

    networks:
      - app_rabbitmq

volumes:
  pgdata:

networks:
  app_postgres:
    driver: bridge
  app_redis:
    driver: bridge
  app_rabbitmq:
    driver: bridge
