FROM dunglas/frankenphp:php8.4-alpine

RUN apk add --no-cache \
    bash \
    git \
    unzip \
    icu-dev \
    libpq-dev \
    linux-headers \
    rabbitmq-c-dev

RUN install-php-extensions \
    pdo_pgsql \
    intl \
    pcntl \
    opcache \
    redis \
    sockets \
    xdebug

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN printf "%s\n" \
  "xdebug.mode=debug,coverage" \
  "xdebug.start_with_request=yes" \
  "xdebug.client_host=host.docker.internal" \
  "xdebug.client_port=60552" \
  "xdebug.idekey=PHPSTORM" \
  "xdebug.log=/tmp/xdebug.log" \
  "xdebug.log_level=7" \
  > /usr/local/etc/php/conf.d/99-xdebug.ini

WORKDIR /opt/project
COPY . .

RUN composer install --no-interaction --prefer-dist

EXPOSE 8000

CMD ["php", "artisan", "octane:start", "--server=frankenphp", "--host=0.0.0.0", "--port=8000", "--watch"]
