FROM php:8.4.5-cli-alpine3.21

RUN set -ex && \
    apk update && \
    apk add --no-cache \
        libpq \
        git \
        nodejs=22.15.1-r0 \
        npm \
        postgresql-dev \
        libzip-dev \
        linux-headers \
        freetype-dev \
        libpng-dev \
        libjpeg-turbo-dev \
        && \
    apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        build-base \
        && \
    docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg \
        && \
    docker-php-ext-configure zip && \
    docker-php-ext-install \
        sockets \
        zip \
        pdo_pgsql \
        gd \
        exif \
        && \
    pecl install redis xdebug && \
    docker-php-ext-enable redis && \
    docker-php-ext-enable xdebug && \
    apk del .build-deps && \
    rm -rf /var/cache/apk/*

COPY --from=composer:2.8.5 /usr/bin/composer /usr/bin/composer

RUN echo "xdebug.mode=coverage" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.start_with_request=no" >> /usr/local/etc/php/conf.d/xdebug.ini

RUN npm install -g corepack
RUN corepack enable && corepack prepare yarn@4.9.4 --activate

WORKDIR /var/www
